//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.09 at 08:48:53 AM CEST 
//


package com.nikedownloader.model.tcx;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Distance_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Distance_t"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Duration_t"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Meters" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Distance_t", propOrder = {
    "meters"
})
public class DistanceT
    extends DurationT
{

    @XmlElement(name = "Meters")
    @XmlSchemaType(name = "unsignedShort")
    protected int meters;

    /**
     * Gets the value of the meters property.
     * 
     */
    public int getMeters() {
        return meters;
    }

    /**
     * Sets the value of the meters property.
     * 
     */
    public void setMeters(int value) {
        this.meters = value;
    }

}
